const ONE_SEC = 1000;

export const TOKEN_POLICY = {
  EXPIRED_TIME_SEC: 600, // sec
  SCHEDULE_INTERVAL_DELETE_EXPIRED_TOKEN: ONE_SEC * 10, // ms
  SCHEDULE_INTERVAL_ACTIVE_TOKEN: ONE_SEC * 15, // ms
  MAX_ACTIVE_TOKEN_COUNT: 5,
} as const;

export const CONCERT_POLICY = {
  EXPIRED_TIME_MIN: 5, // MIN
  SCHEDULE_INTERVAL_DELETE_EXPIRED_SEAT: ONE_SEC * 10, // sec
} as const;
